name: Robot Pengecek Kode

on:
  push:
    branches: [ "main" ]

jobs:
  tes-bisa-jalan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Mengambil Kode dari GitHub
      uses: actions/checkout@v4

    - name: Menyapa Pembuatnya
      run: |
        echo "Halo! Skrip CI/CD pertamamu berhasil dipicu!"
        echo "Robot sedang memeriksa isi folder:"
        ls -la